/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.booking_control;
import Controller.invoice_control;
import Controller.payment_control;
import Model.booking_model;
import Model.connection_model;
import com.toedter.calendar.DateUtil;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author admin
 */
public class dashborad_final extends javax.swing.JFrame {

    /**
     * Creates new form dashborad1
     * 
     
     */
    Color DefaultColor, ClickedClor; 
    public dashborad_final() {
        initComponents();
        
        DefaultColor = new Color(74,31,61);
        ClickedClor = new Color(255,229,173);
        
        pnl_booking.setBackground(DefaultColor);
        pnl_invoice.setBackground(DefaultColor);
        pnl_payment.setBackground(DefaultColor);
        pnl_report.setBackground(DefaultColor);
        pnl_signout.setBackground(DefaultColor);
        
        bookinName();
        invoiceId();
        
        lbl_customerid.setVisible(false);
       
       
       Date dt = new Date();
       
       date_invoice.setDate(dt);
       
       Date date = new Date();
       date_travelling.setMinSelectableDate(date);
       date_due.setMinSelectableDate(date);
       
       
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JTabbedPane();
        pnl_home = new javax.swing.JPanel();
        booking_menu = new javax.swing.JPanel();
        booking = new javax.swing.JPanel();
        lbl_bid = new javax.swing.JLabel();
        txt_bookingid = new javax.swing.JLabel();
        lbl_cname = new javax.swing.JLabel();
        lbl_travelling = new javax.swing.JLabel();
        txt_cname = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        lbl_mail = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        cmb_sevice = new javax.swing.JComboBox<>();
        lbl_service = new javax.swing.JLabel();
        cmb_country = new javax.swing.JComboBox<>();
        lbl_country = new javax.swing.JLabel();
        no_passenger = new javax.swing.JSpinner();
        lbl_noPassenger = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_notes = new javax.swing.JTextArea();
        lbl_notes = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_customerid = new javax.swing.JLabel();
        lbl_vcusomername = new javax.swing.JLabel();
        lbl_vmail = new javax.swing.JLabel();
        lbl_vphone = new javax.swing.JLabel();
        lbl_vservice = new javax.swing.JLabel();
        lbl_vcountry = new javax.swing.JLabel();
        lbl_vpassenger = new javax.swing.JLabel();
        lbl_vdate = new javax.swing.JLabel();
        invoice_menu = new javax.swing.JPanel();
        invoice = new javax.swing.JPanel();
        lbl_bookingid = new javax.swing.JLabel();
        lbl_customername = new javax.swing.JLabel();
        txt_customername = new javax.swing.JTextField();
        lbl_invoicedate = new javax.swing.JLabel();
        lbl_duedate = new javax.swing.JLabel();
        lbl_invoiceid = new javax.swing.JLabel();
        btn_print = new javax.swing.JButton();
        btn_cleari = new javax.swing.JButton();
        cmb_bookingid = new javax.swing.JComboBox<>();
        pnl_cal = new javax.swing.JPanel();
        lbl_description = new javax.swing.JLabel();
        lbl_qty = new javax.swing.JLabel();
        lbl_rate = new javax.swing.JLabel();
        lbl_amount = new javax.swing.JLabel();
        lbl_ticket = new javax.swing.JLabel();
        lbl_cntry = new javax.swing.JLabel();
        lbl_no = new javax.swing.JLabel();
        txt_rate = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        lbl_total = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lbl_invoiceno = new javax.swing.JLabel();
        lbl_custid = new javax.swing.JLabel();
        payment_menu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_inno = new javax.swing.JLabel();
        cmb_invoice = new javax.swing.JComboBox<>();
        lbl_pamount = new javax.swing.JLabel();
        txt_pamount = new javax.swing.JTextField();
        lbl_ppayment = new javax.swing.JLabel();
        txt_ppayement = new javax.swing.JTextField();
        lbl_pbalance = new javax.swing.JLabel();
        txt_balance = new javax.swing.JTextField();
        btn_payment = new javax.swing.JButton();
        btn_pclear = new javax.swing.JButton();
        lbl_vpay = new javax.swing.JLabel();
        report_menu = new javax.swing.JPanel();
        side = new javax.swing.JPanel();
        pnl_invoice = new javax.swing.JPanel();
        lbl_invoice = new javax.swing.JLabel();
        pnl_signout = new javax.swing.JPanel();
        lbl_signout = new javax.swing.JLabel();
        pnl_payment = new javax.swing.JPanel();
        lbl_payment = new javax.swing.JLabel();
        pnl_report = new javax.swing.JPanel();
        lbl_report = new javax.swing.JLabel();
        pnl_booking = new javax.swing.JPanel();
        lbl_booking = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnl_home.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnl_homeLayout = new javax.swing.GroupLayout(pnl_home);
        pnl_home.setLayout(pnl_homeLayout);
        pnl_homeLayout.setHorizontalGroup(
            pnl_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        pnl_homeLayout.setVerticalGroup(
            pnl_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        menu.addTab("", pnl_home);

        booking.setBackground(new java.awt.Color(255, 229, 173));

        lbl_bid.setText("Booking ID");

        txt_bookingid.setEnabled(false);

        lbl_cname.setText("Customer Name");

        lbl_travelling.setText("Date of Travelling");

        txt_cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cnameKeyTyped(evt);
            }
        });

        txt_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_mailKeyTyped(evt);
            }
        });

        txt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneKeyTyped(evt);
            }
        });

        lbl_mail.setText("Mail");

        lbl_phone.setText("Phone");

        cmb_sevice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Air Ticket", "Visa", "Tour" }));
        cmb_sevice.setSelectedIndex(-1);
        cmb_sevice.setToolTipText("");
        cmb_sevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_seviceActionPerformed(evt);
            }
        });

        lbl_service.setText("Service");

        cmb_country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua & Deps", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Central African Rep", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Congo {Democratic Rep}", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland {Republic}", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea North", "Korea South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar, {Burma}", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russian Federation", "Rwanda", "St Kitts & Nevis", "St Lucia", "Saint Vincent & the Grenadines", "Samoa", "San Marino", "Sao Tome & Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad & Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe" }));
        cmb_country.setSelectedIndex(-1);
        cmb_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_countryActionPerformed(evt);
            }
        });

        lbl_country.setText("Country");

        no_passenger.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        no_passenger.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                no_passengerStateChanged(evt);
            }
        });

        lbl_noPassenger.setText("No. Passangers");

        txt_notes.setColumns(20);
        txt_notes.setRows(5);
        jScrollPane1.setViewportView(txt_notes);

        lbl_notes.setBackground(new java.awt.Color(0, 0, 0));
        lbl_notes.setText("Notes");

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        lbl_vcusomername.setText("   ");

        lbl_vmail.setText("   ");

        lbl_vphone.setText("     ");

        lbl_vservice.setText("      ");

        lbl_vcountry.setText("      ");

        lbl_vpassenger.setText("       ");

        lbl_vdate.setText("       ");

        javax.swing.GroupLayout bookingLayout = new javax.swing.GroupLayout(booking);
        booking.setLayout(bookingLayout);
        bookingLayout.setHorizontalGroup(
            bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_clear)
                .addGap(18, 18, 18)
                .addComponent(btn_save)
                .addContainerGap())
            .addGroup(bookingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingLayout.createSequentialGroup()
                        .addGap(0, 138, Short.MAX_VALUE)
                        .addComponent(lbl_customerid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(lbl_bid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bookingid, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(bookingLayout.createSequentialGroup()
                        .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cname, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_service, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_sevice, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bookingLayout.createSequentialGroup()
                        .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_vcusomername, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(bookingLayout.createSequentialGroup()
                                    .addComponent(lbl_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_vmail, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_vservice, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_vcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_vpassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_vphone, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bookingLayout.createSequentialGroup()
                                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_country, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_travelling, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_noPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(no_passenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_vdate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_country, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        bookingLayout.setVerticalGroup(
            bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingLayout.createSequentialGroup()
                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_bid)
                    .addComponent(txt_bookingid, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingLayout.createSequentialGroup()
                        .addComponent(lbl_customerid, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_vcusomername, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_vmail, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_phone))
                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_service)
                            .addComponent(cmb_sevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bookingLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_vphone, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_vservice, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_country))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_vcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_passenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_noPassenger))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_vpassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lbl_travelling)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_vdate, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_notes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout booking_menuLayout = new javax.swing.GroupLayout(booking_menu);
        booking_menu.setLayout(booking_menuLayout);
        booking_menuLayout.setHorizontalGroup(
            booking_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(booking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        booking_menuLayout.setVerticalGroup(
            booking_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(booking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.addTab("", booking_menu);

        invoice.setBackground(new java.awt.Color(255, 229, 173));

        lbl_bookingid.setBackground(new java.awt.Color(0, 0, 0));
        lbl_bookingid.setText("Booking ID");

        lbl_customername.setText("Customer Name");

        txt_customername.setEnabled(false);

        lbl_invoicedate.setText("Invoice Date");

        lbl_duedate.setText("Due Date");

        lbl_invoiceid.setText("Invoice No.");

        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_cleari.setText("Clear");

        cmb_bookingid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb_bookingidFocusGained(evt);
            }
        });
        cmb_bookingid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_bookingidActionPerformed(evt);
            }
        });

        lbl_description.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_description.setText("Description");

        lbl_qty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_qty.setText("Qty");

        lbl_rate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_rate.setText("Rate");

        lbl_amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_amount.setText("Amount");

        lbl_ticket.setPreferredSize(new java.awt.Dimension(0, 16));

        lbl_cntry.setBackground(new java.awt.Color(51, 51, 255));
        lbl_cntry.setPreferredSize(new java.awt.Dimension(0, 16));

        lbl_no.setBackground(new java.awt.Color(51, 51, 255));
        lbl_no.setPreferredSize(new java.awt.Dimension(0, 16));

        txt_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rateActionPerformed(evt);
            }
        });
        txt_rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rateKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rateKeyTyped(evt);
            }
        });

        lbl_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_total.setText("Total");

        txt_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnl_calLayout = new javax.swing.GroupLayout(pnl_cal);
        pnl_cal.setLayout(pnl_calLayout);
        pnl_calLayout.setHorizontalGroup(
            pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_calLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_calLayout.createSequentialGroup()
                        .addGroup(pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_description, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_calLayout.createSequentialGroup()
                                .addGap(18, 48, Short.MAX_VALUE)
                                .addComponent(lbl_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(pnl_calLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lbl_total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_total)
                                .addContainerGap())))
                    .addGroup(pnl_calLayout.createSequentialGroup()
                        .addGroup(pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(pnl_calLayout.createSequentialGroup()
                                .addComponent(lbl_cntry, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_amount))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        pnl_calLayout.setVerticalGroup(
            pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_calLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_description)
                    .addComponent(lbl_qty)
                    .addComponent(lbl_rate)
                    .addComponent(lbl_amount))
                .addGroup(pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_calLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbl_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_calLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_cntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_calLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout invoiceLayout = new javax.swing.GroupLayout(invoice);
        invoice.setLayout(invoiceLayout);
        invoiceLayout.setHorizontalGroup(
            invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(invoiceLayout.createSequentialGroup()
                        .addGroup(invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_duedate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_invoicedate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_customername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lbl_bookingid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_customername)
                            .addComponent(cmb_bookingid, 0, 145, Short.MAX_VALUE))
                        .addGap(136, 136, 136))
                    .addGroup(invoiceLayout.createSequentialGroup()
                        .addComponent(pnl_cal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoiceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_cleari)
                .addGap(18, 18, 18)
                .addComponent(btn_print)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoiceLayout.createSequentialGroup()
                .addComponent(lbl_custid, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_invoiceid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_invoiceno, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        invoiceLayout.setVerticalGroup(
            invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceLayout.createSequentialGroup()
                .addGroup(invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(invoiceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_invoiceno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_invoiceid)))
                    .addComponent(lbl_custid, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(invoiceLayout.createSequentialGroup()
                        .addGroup(invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_bookingid)
                            .addComponent(cmb_bookingid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_customername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_customername))
                        .addGap(36, 36, 36))
                    .addComponent(lbl_invoicedate))
                .addGap(30, 30, 30)
                .addComponent(lbl_duedate)
                .addGap(18, 18, 18)
                .addComponent(pnl_cal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_print)
                    .addComponent(btn_cleari))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout invoice_menuLayout = new javax.swing.GroupLayout(invoice_menu);
        invoice_menu.setLayout(invoice_menuLayout);
        invoice_menuLayout.setHorizontalGroup(
            invoice_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(invoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        invoice_menuLayout.setVerticalGroup(
            invoice_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoice_menuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(invoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.addTab("", invoice_menu);

        jPanel2.setBackground(new java.awt.Color(255, 229, 173));

        lbl_inno.setText("Invoice No.");

        cmb_invoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cmb_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_invoiceActionPerformed(evt);
            }
        });

        lbl_pamount.setText("Amont");

        txt_pamount.setEnabled(false);

        lbl_ppayment.setText("Payement");

        txt_ppayement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ppayementActionPerformed(evt);
            }
        });
        txt_ppayement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ppayementKeyTyped(evt);
            }
        });

        lbl_pbalance.setText("Balance Due");

        txt_balance.setEnabled(false);

        btn_payment.setText("Save");
        btn_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paymentActionPerformed(evt);
            }
        });

        btn_pclear.setText("Clear");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_pclear, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_inno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pamount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ppayment, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pamount, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ppayement, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_vpay, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inno)
                    .addComponent(cmb_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pamount)
                    .addComponent(txt_pamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ppayment)
                    .addComponent(txt_ppayement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_vpay, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pbalance))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_payment)
                    .addComponent(btn_pclear))
                .addContainerGap(296, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout payment_menuLayout = new javax.swing.GroupLayout(payment_menu);
        payment_menu.setLayout(payment_menuLayout);
        payment_menuLayout.setHorizontalGroup(
            payment_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        payment_menuLayout.setVerticalGroup(
            payment_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.addTab("", payment_menu);

        report_menu.setBackground(new java.awt.Color(255, 229, 173));

        javax.swing.GroupLayout report_menuLayout = new javax.swing.GroupLayout(report_menu);
        report_menu.setLayout(report_menuLayout);
        report_menuLayout.setHorizontalGroup(
            report_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        report_menuLayout.setVerticalGroup(
            report_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        menu.addTab("", report_menu);

        side.setBackground(new java.awt.Color(74, 31, 61));
        side.setForeground(new java.awt.Color(255, 255, 255));

        pnl_invoice.setBackground(new java.awt.Color(74, 31, 61));
        pnl_invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_invoiceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_invoiceMousePressed(evt);
            }
        });

        lbl_invoice.setBackground(new java.awt.Color(255, 255, 255));
        lbl_invoice.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        lbl_invoice.setForeground(new java.awt.Color(255, 255, 255));
        lbl_invoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/icons8-invoice-50.png"))); // NOI18N
        lbl_invoice.setText("Invoice");
        lbl_invoice.setIconTextGap(20);

        javax.swing.GroupLayout pnl_invoiceLayout = new javax.swing.GroupLayout(pnl_invoice);
        pnl_invoice.setLayout(pnl_invoiceLayout);
        pnl_invoiceLayout.setHorizontalGroup(
            pnl_invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_invoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_invoiceLayout.setVerticalGroup(
            pnl_invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_invoice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_signout.setBackground(new java.awt.Color(74, 31, 61));
        pnl_signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_signoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_signoutMousePressed(evt);
            }
        });

        lbl_signout.setBackground(new java.awt.Color(255, 255, 255));
        lbl_signout.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        lbl_signout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/icons8-log-out-50.png"))); // NOI18N
        lbl_signout.setText("Sign Out");
        lbl_signout.setIconTextGap(20);
        lbl_signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_signoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_signoutLayout = new javax.swing.GroupLayout(pnl_signout);
        pnl_signout.setLayout(pnl_signoutLayout);
        pnl_signoutLayout.setHorizontalGroup(
            pnl_signoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_signout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_signoutLayout.setVerticalGroup(
            pnl_signoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_signout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_payment.setBackground(new java.awt.Color(74, 31, 61));
        pnl_payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_paymentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_paymentMousePressed(evt);
            }
        });

        lbl_payment.setBackground(new java.awt.Color(255, 255, 255));
        lbl_payment.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        lbl_payment.setForeground(new java.awt.Color(255, 255, 255));
        lbl_payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/icons8-payment-50.png"))); // NOI18N
        lbl_payment.setText("Payment");
        lbl_payment.setIconTextGap(20);

        javax.swing.GroupLayout pnl_paymentLayout = new javax.swing.GroupLayout(pnl_payment);
        pnl_payment.setLayout(pnl_paymentLayout);
        pnl_paymentLayout.setHorizontalGroup(
            pnl_paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_payment, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        pnl_paymentLayout.setVerticalGroup(
            pnl_paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_payment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_report.setBackground(new java.awt.Color(74, 31, 61));
        pnl_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_reportMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_reportMousePressed(evt);
            }
        });

        lbl_report.setBackground(new java.awt.Color(255, 255, 255));
        lbl_report.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        lbl_report.setForeground(new java.awt.Color(255, 255, 255));
        lbl_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/icons8-report-50.png"))); // NOI18N
        lbl_report.setText("Report");
        lbl_report.setIconTextGap(20);

        javax.swing.GroupLayout pnl_reportLayout = new javax.swing.GroupLayout(pnl_report);
        pnl_report.setLayout(pnl_reportLayout);
        pnl_reportLayout.setHorizontalGroup(
            pnl_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_reportLayout.setVerticalGroup(
            pnl_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_booking.setBackground(new java.awt.Color(74, 31, 61));
        pnl_booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_bookingMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_bookingMousePressed(evt);
            }
        });

        lbl_booking.setBackground(new java.awt.Color(255, 255, 255));
        lbl_booking.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        lbl_booking.setForeground(new java.awt.Color(255, 255, 255));
        lbl_booking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icons/icons8-booking-50.png"))); // NOI18N
        lbl_booking.setText("Booking");
        lbl_booking.setAlignmentX(1.0F);
        lbl_booking.setAlignmentY(1.0F);
        lbl_booking.setIconTextGap(20);

        javax.swing.GroupLayout pnl_bookingLayout = new javax.swing.GroupLayout(pnl_booking);
        pnl_booking.setLayout(pnl_bookingLayout);
        pnl_bookingLayout.setHorizontalGroup(
            pnl_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_booking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_bookingLayout.setVerticalGroup(
            pnl_bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_booking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sideLayout = new javax.swing.GroupLayout(side);
        side.setLayout(sideLayout);
        sideLayout.setHorizontalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_booking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_payment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_signout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_invoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideLayout.setVerticalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pnl_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pnl_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pnl_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pnl_report, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pnl_signout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menu))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_invoiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_invoiceMousePressed
        // TODO add your handling code here:
        pnl_booking.setBackground(DefaultColor);
        pnl_invoice.setBackground(ClickedClor);
        pnl_payment.setBackground(DefaultColor);
        pnl_report.setBackground(DefaultColor);
        pnl_signout.setBackground(DefaultColor);
        
        
    }//GEN-LAST:event_pnl_invoiceMousePressed

    private void pnl_signoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_signoutMousePressed
        // TODO add your handling code here:

        pnl_booking.setBackground(DefaultColor);
        pnl_invoice.setBackground(DefaultColor);
        pnl_payment.setBackground(DefaultColor);
        pnl_report.setBackground(DefaultColor);
        pnl_signout.setBackground(ClickedClor);
    }//GEN-LAST:event_pnl_signoutMousePressed

    private void pnl_bookingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_bookingMousePressed
        // TODO add your handling code here:
        pnl_booking.setBackground(ClickedClor);
        pnl_invoice.setBackground(DefaultColor);
        pnl_payment.setBackground(DefaultColor);
        pnl_report.setBackground(DefaultColor);
        pnl_signout.setBackground(DefaultColor);
        
        
    }//GEN-LAST:event_pnl_bookingMousePressed

    private void pnl_paymentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_paymentMousePressed
        // TODO add your handling code here:
        
        pnl_booking.setBackground(DefaultColor);
        pnl_invoice.setBackground(DefaultColor);
        pnl_payment.setBackground(ClickedClor);
        pnl_report.setBackground(DefaultColor);
        pnl_signout.setBackground(DefaultColor);
    }//GEN-LAST:event_pnl_paymentMousePressed

    private void pnl_reportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_reportMousePressed
        // TODO add your handling code here:
        
        pnl_booking.setBackground(DefaultColor);
        pnl_invoice.setBackground(DefaultColor);
        pnl_payment.setBackground(DefaultColor);
        pnl_report.setBackground(ClickedClor);
        pnl_signout.setBackground(DefaultColor);

    }//GEN-LAST:event_pnl_reportMousePressed

    private void pnl_bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_bookingMouseClicked
        // TODO add your handling code here:
        txt_notes.setText("");
         
       booking_control obj = new booking_control();
       
       String booking_id = obj.bookingId();
       String cust_id = obj.customer_Id();

       
       lbl_customerid.setText(cust_id);
       txt_bookingid.setText(booking_id);

        menu.setSelectedIndex(1);
        AutoCompleteDecorator.decorate(cmb_country);
        
    }//GEN-LAST:event_pnl_bookingMouseClicked

    private void pnl_invoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_invoiceMouseClicked
        // TODO add your handling code here:

        menu.setSelectedIndex(2);
        
        invoice_control in = new invoice_control();
       
       String invoice_no = in.invoiceNo();
       lbl_invoiceno.setText(invoice_no);
        
        AutoCompleteDecorator.decorate(cmb_bookingid);
        
        lbl_custid.setVisible(false);
        
        //invoiceId();
        
        //bookinName();
        
    }//GEN-LAST:event_pnl_invoiceMouseClicked

    private void pnl_paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_paymentMouseClicked
        // TODO add your handling code here:
        menu.setSelectedIndex(3);
        AutoCompleteDecorator.decorate(cmb_invoice);
    }//GEN-LAST:event_pnl_paymentMouseClicked

    private void pnl_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_reportMouseClicked
        // TODO add your handling code here:
        menu.setSelectedIndex(4);
        
        try
        {
            JasperDesign jasperDesign = JRXmlLoader.load("C:\\Users\\admin\\Desktop\\DSE\\Sem 2\\EAD\\Projects\\EAD_CW\\src\\View\\revenue.jrxml");
            JRDesignQuery designQuery = new JRDesignQuery();
            designQuery.setText("  SELECT Invoice_No, Description, Invoice_Date, Due_Date, Total FROM Invoice UNION ALL SELECT NULL AS Invoice_No, 'Total Revenue' AS Description, NULL AS Invoice_Date, NULL AS Due_Date, SUM(Total) AS Total FROM Invoice; ");
            jasperDesign.setQuery(designQuery);
            

            
            JasperReport report = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint print = JasperFillManager.fillReport(report,null, connection_model.DatabaseConnect());
            JasperViewer.viewReport(print);
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
        
    }//GEN-LAST:event_pnl_reportMouseClicked

    private void pnl_signoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_signoutMouseClicked
        // TODO add your handling code here:
        
        menu.setSelectedIndex(0);
    }//GEN-LAST:event_pnl_signoutMouseClicked

    private void btn_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paymentActionPerformed
        // TODO add your handling code here:

        try
        {
            if(txt_ppayement.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(null, "Please Enter Payment", "Payment", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                String invoiceId = cmb_invoice.getSelectedItem().toString();
            String custId = lbl_custid.getText();
            String date = ((JTextField)date_invoice.getDateEditor().getUiComponent()).getText();

            int total = Integer.parseInt(txt_pamount.getText());
            int paid = Integer.parseInt(txt_ppayement.getText());

            //int due_amount = total - paid;

            int due = Integer.parseInt(txt_balance.getText());

            payment_control obj = new payment_control();
            obj.insertControl(invoiceId, custId, date,total, paid, due);
            }
            
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }

    }//GEN-LAST:event_btn_paymentActionPerformed

    private void txt_ppayementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ppayementActionPerformed
        // TODO add your handling code here:
        
        

        int total = Integer.parseInt(txt_pamount.getText());
        int paid = Integer.parseInt(txt_ppayement.getText());

        int due_amount = total - paid;
        txt_balance.setText(Integer.toString(due_amount));
        lbl_vpay.setText("");

    }//GEN-LAST:event_txt_ppayementActionPerformed

    private void cmb_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_invoiceActionPerformed
        // TODO add your handling code here:

        amount();

    }//GEN-LAST:event_cmb_invoiceActionPerformed

    private void txt_rateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rateKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_rateKeyTyped

    private void txt_rateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rateKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_rateKeyReleased

    private void txt_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rateActionPerformed
        // TODO add your handling code here:

        int qty = Integer.parseInt(lbl_no.getText());
        int rate = Integer.parseInt(txt_rate.getText());
        int amount = qty * rate;

        txt_amount.setText(Integer.toString(amount));
        txt_total.setText(Integer.toString(amount));
    }//GEN-LAST:event_txt_rateActionPerformed

    private void cmb_bookingidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_bookingidActionPerformed

        customername();
    }//GEN-LAST:event_cmb_bookingidActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed

        try
        {
            //if(cmb_sevice.getSelectedIndex() == -1)
            //{
                //JOptionPane.showMessageDialog(null, "Invoice Details Must Be filled", "Invoice", JOptionPane.INFORMATION_MESSAGE);
            //}
            //else
            //{
                String invoice_no = lbl_invoiceno.getText();
            String booking = cmb_bookingid.getSelectedItem().toString();
            String customer = lbl_custid.getText();
            String description = (lbl_ticket.getText() + " " + lbl_cntry.getText());
            String invoice_date = ((JTextField)date_invoice.getDateEditor().getUiComponent()).getText();
            String due_date = ((JTextField)date_due.getDateEditor().getUiComponent()).getText();
            int total = Integer.parseInt(txt_total.getText());

            invoice_control obj2 = new invoice_control();
            obj2.insertControl(invoice_no, booking, customer, description, invoice_date, due_date, total);
            invoiceId();
            //}
            
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }

        try
        {
            
                JasperDesign jasperDesign = JRXmlLoader.load("C:\\Users\\admin\\Desktop\\DSE\\Sem 2\\EAD\\Projects\\EAD_CW\\src\\View\\invoice.jrxml");
            JRDesignQuery designQuery = new JRDesignQuery();
            designQuery.setText(" SELECT Invoice.Invoice_No, Customer.Customer_Name, Booking.Passenger, Invoice.Description, Invoice.Invoice_Date, Invoice.Due_Date, Invoice.Total FROM Customer JOIN Booking ON Customer.Customer_Id = Booking.Cust_Id JOIN Invoice ON Customer.Customer_Id = Invoice.Cust_Id where Invoice_no = '"+lbl_invoiceno.getText()+"' ");
            jasperDesign.setQuery(designQuery);

            HashMap<String, Object> para = new HashMap<>();
            para.put("Invoice_no", lbl_invoiceno.getText());

            JasperReport report = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint print = JasperFillManager.fillReport(report,para, connection_model.DatabaseConnect());
            JasperViewer.viewReport(print);
            
            
            
            
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }

    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_customername.setText(" ");
        txt_mail.setText(" ");
        txt_phone.setText(" ");
        cmb_sevice.setSelectedIndex(-1);
        cmb_country.setSelectedIndex(-1);
        no_passenger.setValue(0);
        date_travelling.setDate(null);
        txt_notes.setText(" ");

    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:

        try
        {
            if(txt_cname.getText().length() == 0)
            {
                lbl_vcusomername.setText("Provide a Valid Name.");
            }
            else
            {
                lbl_vcusomername.setText("");
            }
            if (txt_mail.getText().length() == 0)
            {
                lbl_vmail.setText("Provide a Valid Mal");
            }
            else
            {
                lbl_vmail.setText("");
            }
            if(!txt_mail.getText().matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-\\+]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$"))
            {
                lbl_vmail.setText("Enter valid Email");
            }
            else
            {
                lbl_vmail.setText("");
            }
            if(txt_phone.getText().length() == 0)
            {
                lbl_vphone.setText("Provide a Valid Phone Number");
            }
            else
            {
                lbl_vphone.setText("");
            }
            if(cmb_sevice.getSelectedIndex() == -1)
            {
                lbl_vservice.setText("Selcet a Service");
            }
            else
            {
                lbl_vservice.setText("");
            }
            if(cmb_country.getSelectedIndex() == -1)
            {
                lbl_vcountry.setText("Select a Country");
            }
            else
            {
                lbl_vcountry.setText("");
            }
            
            int num = Integer.parseInt(no_passenger.getValue().toString());
            
            if(num == 0)
            {
                lbl_vpassenger.setText("Provide No. Passenger");
            }
            else
            {
                lbl_vpassenger.setText("");
            }
            if(date_travelling.getDate() == null)
            {
                lbl_vdate.setText("Select a Date");
            }
            else
            {
                lbl_vdate.setText("");
            }
            if((lbl_vcusomername.getText() == "") && (lbl_vmail.getText() == "") && (lbl_vphone.getText() == "" ) && (lbl_vservice.getText() == "") && (lbl_vcountry.getText() == "") && (lbl_vdate.getText() == "") )
            {
                String customer_id  = lbl_customerid.getText();
                String booking_id = txt_bookingid.getText();
                String name = txt_cname.getText();
                String mail = txt_mail.getText();
                int phone = Integer.parseInt(txt_phone.getText());
                String service = cmb_sevice.getSelectedItem().toString();
                String country = cmb_country.getSelectedItem().toString();
                int passanger = Integer.parseInt( no_passenger.getValue().toString());
                String date = ((JTextField)date_travelling.getDateEditor().getUiComponent()).getText();
                String notes = txt_notes.getText();

                booking_control obj = new booking_control();
                obj.insertControl(customer_id, name, mail, phone, booking_id, service, country, passanger, date, notes);
                
                bookinName();
            }

        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
            lbl_vphone.setText("Type a Only Number");
        }
        if(txt_phone.getText().length() != 10)
        {
            lbl_vphone.setText("Provide a Valid Phone Number");
        }
        else
        {
            lbl_vphone.setText("");
        }

    }//GEN-LAST:event_txt_phoneKeyTyped

    private void txt_cnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cnameKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if(Character.isDigit(c))
        {
            evt.consume();
            lbl_vcusomername.setText("Type a Only Characters");
        }
        
    }//GEN-LAST:event_txt_cnameKeyTyped

    private void txt_cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cnameKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txt_cnameKeyReleased

    private void txt_mailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mailKeyTyped
        // TODO add your handling code here:
        lbl_vcusomername.setText("");
    }//GEN-LAST:event_txt_mailKeyTyped

    private void cmb_seviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_seviceActionPerformed
        // TODO add your handling code here:
        
        lbl_vservice.setText("");
    }//GEN-LAST:event_cmb_seviceActionPerformed

    private void cmb_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_countryActionPerformed
        // TODO add your handling code here:
        lbl_vcountry.setText("");
    }//GEN-LAST:event_cmb_countryActionPerformed

    private void no_passengerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_no_passengerStateChanged
        // TODO add your handling code here:
        lbl_vpassenger.setText("");
    }//GEN-LAST:event_no_passengerStateChanged

    private void txt_cnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cnameKeyPressed
        // TODO add your handling code here
        
    }//GEN-LAST:event_txt_cnameKeyPressed

    private void txt_ppayementKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ppayementKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
            lbl_vpay.setText("Type a Only Number");
        }
    }//GEN-LAST:event_txt_ppayementKeyTyped

    private void cmb_bookingidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb_bookingidFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_bookingidFocusGained

    private void lbl_signoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signoutMouseClicked
        // TODO add your handling code here:
        
        login obj = new login();
        obj.setVisible(true);
        
    }//GEN-LAST:event_lbl_signoutMouseClicked

    
    public void bookinName()
    {
        try
        {
            invoice_control obj = new invoice_control();
            ResultSet result = obj.bookingId();
            
            while(result.next())
            {
                cmb_bookingid.addItem(result.getString(1));  
            }
            
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
    }
    
    public void customername()
    {
        try
        {
            String b_id = cmb_bookingid.getSelectedItem().toString();
            
            invoice_control obj = new invoice_control();
            ResultSet result = obj.name(b_id);
            
            while(result.next())
            { 
                lbl_custid.setText(result.getString(1));
                txt_customername.setText(result.getString(2));
                lbl_ticket.setText(result.getString(3));
                lbl_cntry.setText(result.getString(4));
                lbl_no.setText(result.getString(5));
            }
            
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
    }
    
    
    public void invoiceId()
    {
        try
        {
            payment_control obj = new payment_control();
            ResultSet result = obj.invoice_id();
            
            while(result.next())
            {
                cmb_invoice.addItem(result.getString(1));  
            }
            
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
    }
    
    public void amount()
    {
        try
        {
            String i_no = cmb_invoice.getSelectedItem().toString();
            
            payment_control obj = new payment_control();
            ResultSet result = obj.amount(i_no);
            
            while(result.next())
            { 
                txt_pamount.setText(result.getString(1));
                lbl_custid.setText(result.getString(2));
                
            }
            
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashborad_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashborad_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashborad_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashborad_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashborad_final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel booking;
    private javax.swing.JPanel booking_menu;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_cleari;
    private javax.swing.JButton btn_payment;
    private javax.swing.JButton btn_pclear;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_bookingid;
    private javax.swing.JComboBox<String> cmb_country;
    private javax.swing.JComboBox<String> cmb_invoice;
    private javax.swing.JComboBox<String> cmb_sevice;
    private javax.swing.JPanel invoice;
    private javax.swing.JPanel invoice_menu;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_bid;
    private javax.swing.JLabel lbl_booking;
    private javax.swing.JLabel lbl_bookingid;
    private javax.swing.JLabel lbl_cname;
    private javax.swing.JLabel lbl_cntry;
    private javax.swing.JLabel lbl_country;
    private javax.swing.JLabel lbl_custid;
    private javax.swing.JLabel lbl_customerid;
    private javax.swing.JLabel lbl_customername;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_duedate;
    private javax.swing.JLabel lbl_inno;
    private javax.swing.JLabel lbl_invoice;
    private javax.swing.JLabel lbl_invoicedate;
    private javax.swing.JLabel lbl_invoiceid;
    private javax.swing.JLabel lbl_invoiceno;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_no;
    private javax.swing.JLabel lbl_noPassenger;
    private javax.swing.JLabel lbl_notes;
    private javax.swing.JLabel lbl_pamount;
    private javax.swing.JLabel lbl_payment;
    private javax.swing.JLabel lbl_pbalance;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_ppayment;
    private javax.swing.JLabel lbl_qty;
    private javax.swing.JLabel lbl_rate;
    private javax.swing.JLabel lbl_report;
    private javax.swing.JLabel lbl_service;
    private javax.swing.JLabel lbl_signout;
    private javax.swing.JLabel lbl_ticket;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_travelling;
    private javax.swing.JLabel lbl_vcountry;
    private javax.swing.JLabel lbl_vcusomername;
    private javax.swing.JLabel lbl_vdate;
    private javax.swing.JLabel lbl_vmail;
    private javax.swing.JLabel lbl_vpassenger;
    private javax.swing.JLabel lbl_vpay;
    private javax.swing.JLabel lbl_vphone;
    private javax.swing.JLabel lbl_vservice;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JSpinner no_passenger;
    private javax.swing.JPanel payment_menu;
    private javax.swing.JPanel pnl_booking;
    private javax.swing.JPanel pnl_cal;
    private javax.swing.JPanel pnl_home;
    private javax.swing.JPanel pnl_invoice;
    private javax.swing.JPanel pnl_payment;
    private javax.swing.JPanel pnl_report;
    private javax.swing.JPanel pnl_signout;
    private javax.swing.JPanel report_menu;
    private javax.swing.JPanel side;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JLabel txt_bookingid;
    private javax.swing.JTextField txt_cname;
    private javax.swing.JTextField txt_customername;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextArea txt_notes;
    private javax.swing.JTextField txt_pamount;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_ppayement;
    private javax.swing.JTextField txt_rate;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
